### ISSUE TITLE
Not able to switch pid-mode to auto

### ISSUE THREAD

**Issue by jorometala** [ScratMan/HASmartThermostat#102]
**Describe the bug**
After autotune successfully done pid mode automatically is set to auto which is good. But if i set , k params in config.yaml and restart HA, autotune start over, If autotune is disabled in config I'm not able to switch to pid mode auto. Service executes without error but pid-mode stays off 

**To Reproduce**
1 set K params manually in config
2 set pid-mode to auto

**Expected behavior**
Pid mode in the status entity to be set to auto

**Additional context**

**Comment by ScratMan** [comment]
Hi, please post your configuration Yaml once auto-tune is disabled.

**Comment by jorometala** [comment]
Here is the configuration.yaml
`climate:
  - platform: smart_thermostat
    name: Smart Thermostat livingroom
    unique_id: Livingroom Heating
    heater: switch.shellyplus1_083af2027874
    target_sensor: sensor.livingroom_h_and_t_temperature
    min_temp: 10
    max_temp: 28
    ac_mode: False
    comfort_temp: 21
    noiseband: 0.2
    target_temp: 21
    #autotune: "pessen-integral"
    autotune: "off"
    keep_alive:
      seconds: 60
    away_temp: 14
    kp: 45.47284088339883
    ki: 0.15898451616875717
    kd: 4889.536679696049
    pwm: 00:15:00`
    
and the status of the entity after I trigger the pid_mode set service to auto 
`hvac_modes:
  - heat
  - 'off'
min_temp: 10
max_temp: 28
preset_modes:
  - none
  - away
  - comfort
current_temperature: 20.9
temperature: 21
hvac_action: idle
preset_mode: none
away_temp: 14
eco_temp: null
boost_temp: null
comfort_temp: 22
home_temp: null
sleep_temp: null
activity_temp: null
control_output: 0
Kp: 45.47284088339883
Ki: 0.15898451616875717
Kd: 4889.536679696049
Ke: 0
pid_mode: 'off'
pid_p: 0
pid_i: 0
pid_d: 0
pid_e: 0
pid_dt: 0
autotune_status: 'off'
autotune_sample_time: null
autotune_tuning_rule: 'off'
autotune_set_point: null
autotune_peak_count: 0
autotune_buffer_full: 0
autotune_buffer_length: 10
friendly_name: Livingroom heating
supported_features: 17
`

**Comment by ScratMan** [comment]
Please try commenting the autotune: "off" line in configuration Yaml.

**Comment by jorometala** [comment]
I have done it and here is the result: 
`hvac_modes:
  - heat
  - 'off'
min_temp: 10
max_temp: 28
preset_modes:
  - none
  - away
  - comfort
current_temperature: 21.5
temperature: 21
hvac_action: idle
preset_mode: none
away_temp: 14
eco_temp: null
boost_temp: null
comfort_temp: 22
home_temp: null
sleep_temp: null
activity_temp: null
control_output: 0
Kp: 45.47284088339883
Ki: 0.15898451616875717
Kd: 4889.536679696049
Ke: 0
pid_mode: 'off'
pid_p: 0
pid_i: 0
pid_d: 0
pid_e: 0
pid_dt: 0
autotune_status: 'off'
autotune_sample_time: 0
autotune_tuning_rule: none
autotune_set_point: 0
autotune_peak_count: 0
autotune_buffer_full: 0
autotune_buffer_length: 0
friendly_name: Livingroom heating
supported_features: 17
`

**Comment by jorometala** [comment]
actually after turning pid_mode to auto from the service this time make a difference and:
`hvac_modes:
  - heat
  - 'off'
min_temp: 10
max_temp: 28
preset_modes:
  - none
  - away
  - comfort
current_temperature: 21.5
temperature: 21
hvac_action: idle
preset_mode: none
away_temp: 14
eco_temp: null
boost_temp: null
comfort_temp: 22
home_temp: null
sleep_temp: null
activity_temp: null
control_output: 0
Kp: 45.47284088339883
Ki: 0.15898451616875717
Kd: 4889.536679696049
Ke: 0
pid_mode: auto
pid_p: -22.7
pid_i: 0
pid_d: 0
pid_e: 0
pid_dt: 370.34221029281616
autotune_status: 'off'
autotune_sample_time: 0
autotune_tuning_rule: none
autotune_set_point: 0
autotune_peak_count: 0
autotune_buffer_full: 0
autotune_buffer_length: 0
friendly_name: Livingroom heating
supported_features: 17

`
do you see anything wrong in these values?

**Comment by ScratMan** [comment]
OK, understood. The `autotune: "off"` line will try to enable the autotuner with the "off" rule that doesn't exist, so the PID is forced off until the auto-tune is done, but autotuner remains off because rule is not recognised.
