### ISSUE TITLE
Option to guarantee at least n zones on every moment in order not to damage the water pump

### ISSUE THREAD

**Issue by TheNico14** [ScratMan/HASmartThermostat#104]
First of all, thank you for your excellent work on this project!

To avoid damaging the water pump in my heatpump and to reduce the number of cycles/hour of the system it is necessary to ensure a minimum flow of water in the pipes. I would like to have at least n zones turned on at each instant to ensure a minimum water flow.

The functionality can be handled with automations by switching off the zone control and turning manually on the zone for a specified time, but in large systems it easily becomes difficult to manage.
A way to achieve this is could be by setting a minimum time for the zone to be on and a time offset between the start of the different cycles. This way, by overlapping the desired zones via the time offset, a safe minimum flow can always be achieved.

**Comment by IacopoOrtis** [comment]
Hi! There already is a parameter that can be used as you intend. It's not exactly what you are asking for but if you use it correctly I beleive it can mitigate your problem. Please have a look at "min_cycle_duration".

**Comment by ScratMan** [comment]
If you need to keep the circulator on, you should install a bypass on the circuit.
