### ISSUE TITLE
attribute hvac_action no longer present since update to 2023.1.0

### ISSUE THREAD

**Issue by Motik68** [ScratMan/HASmartThermostat#115]
**Describe the bug**
The `hvac_action` attribute, which used to tell whether the thermostat was heating or idle, is no longer present.

**To Reproduce**
Update to 2023.1.0

**Expected behavior**
`hvac_action` attribute with value `idle` or `heating`.

**Screenshots**
```
hvac_modes:
  - heat
  - 'off'
min_temp: 7
max_temp: 30
preset_modes:
  - none
  - away
  - eco
  - comfort
  - sleep
current_temperature: 22.6
temperature: 22.5
preset_mode: comfort
away_temp: 16
eco_temp: 22
boost_temp: null
comfort_temp: 22.5
home_temp: null
sleep_temp: 21
activity_temp: null
control_output: 0
kp: 100
ki: 0.001
kd: 0
ke: 0
pid_mode: 'off'
pid_p: -10
pid_i: 0
pid_d: -0.0
pid_e: 0
pid_dt: 60.34237480163574
friendly_name: Chambre
supported_features: 17
```
**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Migelo** [comment]
I am running
```
 Home Assistant 2023.1.7 
Supervisor 2023.01.1 
Operating System 9.5 
Frontend 20230110.0 - latest 
```

and `hvac_action` is present.

I recommend you create another `smart_thermostat` instance with a different name and see if `hvac_action` shows there.

**Comment by Motik68** [comment]
Thanks for the input Migelo. Are you also running the latest version of `smart_thermostat` (2023.1.0)?

**Comment by pantgr** [comment]
same problem hear, i make the step to recreate the entity not helps also the pid mode is off all the time.

**Comment by Motik68** [comment]
Created a new instance with a different name as suggested by Migelo and rebooted, and still no `hvac_action`...

**Comment by spider7611** [comment]
Have problem too. My simple thermostat card disappered from my dashboard after update. :(

**Comment by pantgr** [comment]
Temporary Roll Back to previous version and all work as expected , This indicates the fault is in new version and have nothing to HA.
