### ISSUE TITLE
Existing thermostats not correctly initialised on HA restart (including PID mode reverting to off)

### ISSUE THREAD

**Issue by Motik68** [ScratMan/HASmartThermostat#116]
**Describe the bug**
Since updating to 2023.1.0, my (already existing) thermostats revert to the values from `configuration.yaml` when I restart HA, instead of taking the latest values from the database (kp, ki, etc.)

This includes resetting PID mode to off, although it had been set to auto (and confirmed working) prior to restarting.

**To Reproduce**
Update to 2023.1.0

**Expected behavior**
As in previous versions: keep the thermostat's prior configuration (kp, ki, etc.) on reboot.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by ScratMan** [comment]
Should be fixed in [2023.1.1](https://github.com/ScratMan/HASmartThermostat/releases/tag/2023.1.1)
