### ISSUE TITLE
Heating status is stuck

### ISSUE THREAD

**Issue by crux2006** [ScratMan/HASmartThermostat#118]
Hi, even if the managed heating device changes state, this is not reflected in the heating integration. Maybe the video was not explanatory, but if you pay attention, even if the relay is turned on and off, the heating is constantly on.

Is this bug only me... Version 2023.

https://user-images.githubusercontent.com/59333074/215348199-08eb1815-5fae-4b57-a3d4-bafe01293f10.mp4

**Comment by ScratMan** [comment]
Please try 2023.1.1

**Comment by crux2006** [comment]
updated, problem fixed. How to write Pid_p , Pid_i , Pid_d entities in yaml directory?

  pid_e_debug: true
 
  It doesn't happen this way. Can you give a short example?

**Comment by ScratMan** [comment]
Write `debug: true` in the configuration Yaml and reload the integration or restart HA. The `pid_'x'` attributes will then appear in the entity's state.

**Comment by crux2006** [comment]
Thanks:) You can close the topic if you wish.
