### ISSUE TITLE
'Smart thermostat heating' not shown anymore in history graph

### ISSUE THREAD

**Issue by david-cuenca-bcn82** [ScratMan/HASmartThermostat#119]
With the latest updates the history graph stopped painting the orange vertical bars representing the smart thermostat heating periods. What may I do to make those orange bars to be painted again?
Thank you very much for your help!

**Comment by ScratMan** [comment]
There was an issue in release 2023.1.0, please update to 2023.1.1

**Comment by david-cuenca-bcn82** [comment]
Thank you very much @ScratMan
