### ISSUE TITLE
After update no pid_p and pid_d sensor. :(

### ISSUE THREAD

**Issue by spider7611** [ScratMan/HASmartThermostat#120]
After update 2023.1.1 get this error in HA log. 

TemplateError('ValueError: Template error: float got invalid input 'None' when rendering template '{{ state_attr('climate.gyerekszoba', 'pid_p') | float }}' but no default was specified') while processing template 'Template("{{ state_attr('climate.gyerekszoba', 'pid_p') | float }}")' for attribute '_attr_native_value' in entity 'sensor.smart_thermostat_p'
TemplateError('ValueError: Template error: float got invalid input 'None' when rendering template '{{ state_attr('climate.gyerekszoba', 'pid_d') | float }}' but no default was specified') while processing template 'Template("{{ state_attr('climate.gyerekszoba', 'pid_d') | float }}")' for attribute '_attr_native_value' in entity 'sensor.smart_thermostat_d'

Error while processing template: Template("{{ state_attr('climate.gyerekszoba', 'pid_p') | float }}")
Error while processing template: Template("{{ state_attr('climate.gyerekszoba', 'pid_d') | float }}")

pid_p and pid_d not changing.
Only pid_i and pid_output changing like before update.

**Comment by ScratMan** [comment]
Hello, pid_p, pid_d and pid_e are now removed by default from attributes to limit thermostat's footprint in the HA database. To bring them back please add `debug: true` in the Yaml.

**Comment by spider7611** [comment]
Ohh ok, thank you!
