### ISSUE TITLE
Multiple entity_ids configurable for "heater" parameter

### ISSUE THREAD

**Issue by martinlie** [ScratMan/HASmartThermostat#124]
**Is your feature request related to a problem? Please describe.**
At the moment, multiple zones connected to one thermostat must use Boolean Inputs and Automation in addition to the Smart Thermostat. This makes the HA configuration more complex than necessary and prone to errors.

**Describe the solution you'd like**
Basically, the *heater* entity_id should accept a yaml array of entities (actuator relays) that are controlled simultaneously. We should expect that there is only one PWM output setting (valve or actuator) for all entities.

I am not aware of a possibility for this today.

**Describe alternatives you've considered**
Currently, I have multiple heating actuators connected to one PID thermostat. The underfloor heating area in some of our house's zones are heated using multiple loops of heating, with one actuator per loop. Each actuator is controlled via a Z-Water relay via the Z-Wave bus. For those zones with multiple actuators in the same room, I must use Automation to control these loops via a Boolean input, which is then connected to one PID thermostat. This works, but is unnecessarily complex.

An alternative is multiple instances of the same PID thermostat for the same room, but this creates a problem for the user who must fiddle with three thermostats for the same room with separate configuration, history etc. (not a solution).

**Additional context**
We ripped out the old heating control system during Christmas and invested in HA, Z-water relays and Heat-It room sensors, connected via a Proxmox installed on an i7 ThinkCenter. All rooms are controlled by the Smart Thermostat with external temperature compensation, with association groups set up in the Z-wave network as backup. Works like a charm, the heat in the house is more stable than ever and the 12kW heat pump is able to comfortably heat our house during cold weather (-10 to -20 *C), which it was on the edge of coping with earlier due to thermostat hysteresis going out of control. We have 12 zones controlled by PID, very nice integration and the sole reason for us to choose HA!

**Comment by martinlie** [comment]
It might be the solution is to use the Group helper integration, grouping several switches -- I will check it out. If so, that might be a more generic solution.

**Comment by martinlie** [comment]
The Group helper seems to be a viable solution! I was made aware of this function in the latest newsletter, documentation at [https://www.home-assistant.io/integrations/group/]. Tested and working as expected.

**Comment by ScratMan** [comment]
Great news !
