### ISSUE TITLE
Still heating after setpoint is reached

### ISSUE THREAD

**Issue by andriuskr** [ScratMan/HASmartThermostat#139]
Why thermostat is still heating after setpoint is reached?
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/13429780/224468811-80634963-5719-449f-8209-fd34a609ec56.png">

  - platform: smart_thermostat
    name: Justina Workplace Floor
    unique_id: justina_workplace_floor
    heater: switch.under_conditioner
    target_sensor: sensor.tasmota_ds18b20_temperature
    min_temp: 16
    max_temp: 31
    ac_mode: False
    target_temp: 29
    keep_alive:
      seconds: 60
    away_temp: 14
    kp: 5
    ki: 0.01
    kd: 500
    pwm: 00:15:00

**Comment by ScratMan** [comment]
Hello, enable debug mode and look at the values of pid_p, pid_i, pid_d and pid_e attributes. Their sum controls the PID output.

**Comment by Chupaka** [comment]
Hey @andriuskr , looks like your `kp` and/or `ki` values are too low, so it takes some time for PID controller to increase its output and heat more to compensate temperature drop. As **ScratMan** told, enable `debug` mode in [Parameters](https://github.com/ScratMan/HASmartThermostat#parameters) and draw your pid_p, pid_i, pid_d values to see a proportion between them and their dynamics.
