### ISSUE TITLE
Feature request - Addition of 0.01 precision

### ISSUE THREAD

**Issue by konpyl** [ScratMan/HASmartThermostat#140]
I am currently utilizing a circadian cycle temperature system that involves a gradual transition of temperature. I would like to kindly request the addition of 0.01 precision, as this would result in an even smoother and more seamless temperature transition.

**Comment by Chupaka** [comment]
Sorry, precision depends on Home Assistant constants, so it needs to be added to Home Assistant first. Currently they have only 1, 0.5 and 0.1: https://github.com/home-assistant/core/blob/7010447b04be53d4c9f1cc696cd9210f87611d90/homeassistant/const.py#L1138
