### ISSUE TITLE
Generic setpoint control with appropriate units rather than temperature

### ISSUE THREAD

**Issue by ArrEssJay** [ScratMan/HASmartThermostat#145]
**Is your feature request related to a problem? Please describe.**
I need to control a dehumidifier instead of a heater. Everything else except the units is the same. Indeed, we can look at this as an abstract control problem rather than 'thermostat'. We have the setpoint, and the current value. Whether it's temperature or humidity or water level is irrelevant to the control loop. It only matters when displaying the values.

**Describe the solution you'd like**
Change configuration to setpoint min/max and desired units.

**Describe alternatives you've considered**
Ignore that temperature is really 'some other controlled parameter'.

**Comment by ScratMan** [comment]
Hi, the "temperature" is inherited from the generic thermostat. Changing this means rewriting the full integration.
