### ISSUE TITLE
Warning in log file after update to Home Assistant 2023.5.0

### ISSUE THREAD

**Issue by stanol** [ScratMan/HASmartThermostat#149]
`Entity climate.smart_thermostat (<class 'custom_components.smart_thermostat.climate.SmartThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.`

Home Assistant version: 2023.5.0
HASmartThermostat version: 2023.2.1

**Comment by Moshkopp** [comment]
Same here.

`Entity climate.trv_wz (<class 'custom_components.better_thermostat.climate.BetterThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
Entity climate.trv_bad (<class 'custom_components.better_thermostat.climate.BetterThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
`
