### ISSUE TITLE
Cannot use input number as heater entity

### ISSUE THREAD

**Issue by Rudd-O** [ScratMan/HASmartThermostat#160]
**Describe the bug**

With PWM turned off (0) the heater entity is being used by this integration as a floating point number store.  Which is good.  I want this.

Unfortunately, using an input number helper does not work:

```
Jul 13 00:52:41 assistant hass[22855]: 2023-07-13 00:52:41.677 INFO (MainThread) [custom_components.smart_thermostat.climate] climate.living_space: Change state of input_number.living_space_climate_pid_output to -1.7
Jul 13 00:52:41 assistant hass[22855]: 2023-07-13 00:52:41.677 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities input_number.living_space_climate_pid_output or it is/they are currently not available
```

The number entity is certainly available.

Here is the bug:

![image](https://github.com/ScratMan/HASmartThermostat/assets/346306/7e598864-2f3d-4880-b535-b4ce8cb50742)

Can't call the NUMBER domain on an INPUT_NUMBER entity.

**Comment by ScratMan** [comment]
Hi.
Please try with [v2023.7.0-beta2](https://github.com/ScratMan/HASmartThermostat/releases/tag/2023.7.0-beta2)

**Comment by Chupaka** [comment]
Please close the issue as it's released already?..
