### ISSUE TITLE
could not convert string to float: 'off'

### ISSUE THREAD

**Issue by Hood-fr** [ScratMan/HASmartThermostat#178]
in climate.py, line 974 : return float(self.hass.states.get(self.heater_or_cooler_entity).state) > 0

I get the recurrent error which fails the integration of HASmartThermostat : could not convert string to float: 'off'

Integration on a docker container within a Synology NAS.

**Comment by Chupaka** [comment]
What's your config? Have you set `pwm` parameter?

**Comment by Hood-fr** [comment]
Pnw set to 0 as recommended by documentation for heater entity with direct input

**Comment by Chupaka** [comment]
> If a valve is used, pwm parameter should be set to 0.

You mean this part? But valve's state should be numeric, 0-100. Your 'off' value says it's more switch than valve...

**Comment by Hood-fr** [comment]
OK got it, thanks.
