### ISSUE TITLE
Use as a moisture control device (fan)

### ISSUE THREAD

**Issue by RubenKelevra** [ScratMan/HASmartThermostat#19]
I would like to use this to activate/deactivate the fan in my bathroom. Any chance to extend the functionality like that?

**Comment by ScratMan** [comment]
Hello, IMHO, there is nothing to be extended. This thermostat can control any system based on a sensor and a switch when time based modulation is possible. The limitation might be from Home Assistant limiting unit to °C or °F, as this impacts the sensor display precision and set point steps.
