### ISSUE TITLE
pid_p pid_d

### ISSUE THREAD

**Issue by gkrallo** [ScratMan/HASmartThermostat#195]
issue

Why doesnt debug parameters pid_p and pid_i show up?
I only get pid_i
It hoper seems to be i and p parts in the control loop
kind regards
Kristian 

![Screenshot_20231229_180141_Home Assistant](https://github.com/ScratMan/HASmartThermostat/assets/96731141/4f4010a3-e251-4a1c-a854-cf7feb66da13)

**Comment by Chupaka** [comment]
You need to set `debug: true` in your climate's config. pid_i is always shown.

**Comment by gkrallo** [comment]
AHA ok thanks
Is that possible to read about somewhere?
Thanks again
kp

**Comment by Chupaka** [comment]
Sure, it's in README:

> debug (Optional): Make the climate entity expose the following internal values as extra states attributes <...>
Available debug attributes are:
pid_p
pid_i
pid_d
pid_e
pid_dt
