### ISSUE TITLE
Strange behavior with 2024.1 ha

### ISSUE THREAD

**Issue by andyinno** [ScratMan/HASmartThermostat#197]
**Describe the bug**

The thermostat is overshooting

**Expected behavior**
The PID should align with the temperature defined in the thermostat 

**Screenshots**
![Screenshot_2024-01-09-17-15-15-41_c3a231c25ed346e59462e84656a70e50](https://github.com/ScratMan/HASmartThermostat/assets/5983066/ca783caf-eee5-487f-9469-095bab040962)

This is my current configuration 

![Screenshot_2024-01-09-17-21-56-35_c3a231c25ed346e59462e84656a70e50](https://github.com/ScratMan/HASmartThermostat/assets/5983066/0059cdd3-362d-449c-b3a8-fde7ff12ebee)

I have other 3 thermostats configured and the other three are behaving correctly.

Do you experienced some behavior similar to this? Or there is something that my eye can't catch in the configuration?

The house is really well insulated and the heating is a floor heating

Thank you in advance

**Comment by ScratMan** [comment]
Didn't see this. Using four instances without issue on 2024.1.2 here.
Add the `debug: true` line to your config, restart HA and look at the values of `pid_(X)` attributes if the issue is still present.

**Comment by andyinno** [comment]
I kept it monitored in the last 3 days.

After reboot I turned off and on again the smart thermostat entity and never occurred.
Sorry for the noise. Not related to 2024.1 and not able to replicate it
