### ISSUE TITLE
Keep_alive not working

### ISSUE THREAD

**Issue by HappyPlotter** [ScratMan/HASmartThermostat#201]
**Describe the bug**
The thermostat is controlling a shelly device. I have enabled the keep_alive to 1 minute and in the shelly I have the timer off set to 10 minutes. Normally the timer should be reset back to 10 minutes every keep_alive period so every minute in my configuration

**To Reproduce**
Set the keep_alive to 1 minute and check if it updates the value

**Additional context**
keep_alive works fine with generic thermostat, it is not woking correctly with dual thermostat

**Comment by tantra35** [comment]
In my case, i relatively fixed this by setting `min_cycle_duration`, and its seems to work

**Comment by HappyPlotter** [comment]
I have minimum cycle set but it does not fix the keepalive. I have not made an automation that every minute turns on the shelly. Which essentially "keeps alive"

**Comment by ScratMan** [comment]
> I have minimum cycle set but it does not fix the keepalive. I have not made an automation that every minute turns on the shelly. Which essentially "keeps alive"

Please test the alpha release [v2024.6.2-alpha1](https://github.com/ScratMan/HASmartThermostat/releases/tag/keep_alive_fix), if it fixes it I'll make it official.

**Comment by HappyPlotter** [comment]
It might take a while until I get my hands on another shelly. The one that is on the heater is not easy to be removed/tested since now we have 35+ degrees

**Comment by ScratMan** [comment]
Disconnect the heater, and plug the Shelly on a light (or an ohmmeter if it's a dry contacts relay switch).
