### ISSUE TITLE
Feature request - Multiple heater entities

### ISSUE THREAD

**Issue by herrar1** [ScratMan/HASmartThermostat#213]
As a feature request multiple heater entities would be helpful addition.
Wouldn't it be easier to edit the code directly. Using helpers to merge multiple heater entities together just adds complexity. As if one room has multiple radiators.

**Comment by M-ERiMiEs** [comment]
Im also interested about the subject tho I have multi circuit underfloor heating. Adding factor to redure outputs according the lenght of circuit for hydraulic balancing of the system would be suberb.

**Comment by ScratMan** [comment]
Added in [v2024.4.0-beta1](https://github.com/ScratMan/HASmartThermostat/releases/tag/2024.4.0-beta1)
