### ISSUE TITLE
thermostat in off mode still controlls devices

### ISSUE THREAD

**Issue by ploeffler** [ScratMan/HASmartThermostat#218]
I am using smart_thermostat to cool an enclosure with 2 raspberry-pi in it.
the target sensor is the average of both cpu-temperatures.
the the "heater" are two fans.
I am using the outside_sensor.

everything works es expected, but: if I switch to mode "off" the controller still disactivates the fan, when I manually switch them on.

**Comment by ScratMan** [comment]
Hello, it's the default behavior. As the "OFF" command may be missed by wireless devices, the thermostat by default regularly sends this OFF command to ensure the heater is not left ON while it should be OFF.

You can disable this by adding the following setting to your Smart Thermostat entity in the YAML configuration file:
`force_off_state: false`
