### ISSUE TITLE
No unique_id

### ISSUE THREAD

**Issue by papadi** [ScratMan/HASmartThermostat#22]
The generic thermostat has a unique_id property so that we can explicitly specify the id instead of getting a random one. It would be nice if we can have that in this component. :)

**Comment by ScratMan** [comment]
Hello, please test the new [2021.11.9-beta1 release](https://github.com/ScratMan/HASmartThermostat/releases/tag/2021.11.9-beta1)

**Comment by papadi** [comment]
Thx. I followed your instructions and I got no errors. So I guess it's ok?
When I rename the sensor in the yaml and restart HA however, the result is that I get a _1, _2 suffix. I don't know if this is expected. Do I always need to stop HA, rename and yaml and then start it again? Not sure what the expected behaviour is.
In any case, for new entities it should work. Thx again.

**Comment by ScratMan** [comment]
> When I rename the sensor in the yaml and restart HA however, the result is that I get a _1, _2 suffix. I don't know if this is expected.

This can occur. The old entity should be visible and marked as unavailable in the development tools, next to the new one with _2 or _3 that is working.
You can edit the old entity in HA to remove it, and then edit the duplicated one to remove the _2 or _3 from the ID field.

**Comment by ScratMan** [comment]
Closed with [release v2021.11.9](https://github.com/ScratMan/HASmartThermostat/releases/tag/2021.11.9)
