### ISSUE TITLE
New PID i behavior?

### ISSUE THREAD

**Issue by HermesHonshappo** [ScratMan/HASmartThermostat#265]
## **Describe the bug**
Hello 

First of all, I'd like to thank you for the add-on. It is amazing, and I've been using it for the third year (I think)
It generated both €€€ savings, and a higher level of flexibility and comfort in our home

Now for the questions: I noticed two new behaviors for the "i" component of the PID. I don't think I noticed them before, but I could be mistaken. Honestly, I'm not sure if this is a bug or a feature. I checked the documentation but didn't see any mention of this.

## 1) i goes negative

Exemple below

![image](https://github.com/user-attachments/assets/297f962e-b8bf-48bd-b8d2-505c01f518f1)

During the first step-up of the target temp, we see that the result temperature slightly overshoots. As a consequence, the i factor becomes negative. 
I'm not sure if this is normal or not

## 2) i resets when there is a change in target temperature

Exemple below

![image](https://github.com/user-attachments/assets/0113f8d7-0904-45d9-ab06-e9f98dfa855a)

We see a short drop in target temp. This is due to a presence timer (when noone home for more than 1 hour, set all presets to "away" 15°C). We came back shortly after this period, and the target temp was restored to "comfort" (18°C)

As the graph shows, the i component, which had stabilized in the long "comfort" period before is reset to zero
Here as well, I'm not sure if this is normal or not

## **Expected behavior**
I am unsure if the above are issues or features to be honest.
If features, I'd be interested to see in the documentation if they can be turned on and off, and if there are parameters to adjust the features

## **Desktop (please complete the following information):**
 - OS: HAOS 
 - Home assistant versions :
   - Core 2024.11.3
   - Supervisor 2024.11.4
   - Operating System 13.2
   - Frontend 20241106.2
 - add-on version: 2024.6.1

**Comment by ScratMan** [comment]
Since 2024.6.0, the integral `pid_i` part can go negative down to external `-pid_e` to avoid overheating issues due to Ke gain. Hence the Ki and Ke gains might be readjusted.
Also, the integral part is cleared when set point is changed as it should converge to a new value.
This behaviour should help having faster reactivity on the heating by allowing higher Ki gains without overheating.

**Comment by HermesHonshappo** [comment]
I did nt notiec this change before. Sorry for opening the issue, then.
If I understand right, if the current value of `pid_e` is 20%, it means that `pid_i` can go negative and down to -20%?

**Comment by ScratMan** [comment]
Correct.

**Comment by HermesHonshappo** [comment]
Thanks. closing the issue, then (since it's not even an issue, but a feature I wasn't aware of)
