### ISSUE TITLE
Integral resets on HA restart

### ISSUE THREAD

**Issue by andreid1303** [ScratMan/HASmartThermostat#266]
**Describe the bug**

It happens to me again and again. Tried to uninstall and install the integration. Does not help.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - HA VM on Proxmox host

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andreid1303** [comment]
![Снимок экрана 2024-12-04 в 16 50 44](https://github.com/user-attachments/assets/14fb7090-774b-4929-b751-e1fed2d4290e)

**Comment by andreid1303** [comment]
`climate:
  - platform: smart_thermostat
    name: House Smart Thermostat
    unique_id: e66af15f-b622-4044-81e7-8717816cdbf5
    target_sensor: sensor.house_temperature
    outdoor_sensor: sensor.climate_outdoor_temperature
    heater: input_number.boiler_output
    pwm: 0
    keep_alive:
      seconds: 60
    min_temp: 7
    max_temp: 25
    target_temp: 21
    away_temp: 14
    eco_temp: 10
    # boost_temp: 4
    comfort_temp: 19
    home_temp: 21.5
    sleep_temp: 19
    activity_temp: 18
    sensor_stall: 00:30:00
    output_safety: 50.0
    debug: true
`

**Comment by andreid1303** [comment]
`
climate:
  - platform: smart_thermostat
    name: House Smart Thermostat
    unique_id: e66af15f-b622-4044-81e7-8717816cdbf5
    target_sensor: sensor.house_temperature
    outdoor_sensor: sensor.climate_outdoor_temperature
    heater: input_number.boiler_output
    pwm: 0
    keep_alive:
      seconds: 60
    min_temp: 7
    max_temp: 25
    target_temp: 21
    away_temp: 14
    eco_temp: 10
    # boost_temp: 4
    comfort_temp: 19
    home_temp: 21.5
    sleep_temp: 19
    activity_temp: 18
    sensor_stall: 00:30:00
    output_safety: 50.0
    debug: true
`

**Comment by andreid1303** [comment]
``
climate:
  - platform: smart_thermostat
    name: House Smart Thermostat
    unique_id: e66af15f-b622-4044-81e7-8717816cdbf5
    target_sensor: sensor.house_temperature
    outdoor_sensor: sensor.climate_outdoor_temperature
    heater: input_number.boiler_output
    pwm: 0
    keep_alive:
      seconds: 60
    min_temp: 7
    max_temp: 25
    target_temp: 21
    away_temp: 14
    eco_temp: 10
    comfort_temp: 19
    home_temp: 21.5
    sleep_temp: 19
    activity_temp: 18
    sensor_stall: 00:30:00
    output_safety: 50.0
    debug: true
``

**Comment by andreid1303** [comment]
climate:
  - platform: smart_thermostat
    name: House Smart Thermostat
    unique_id: e66af15f-b622-4044-81e7-8717816cdbf5
    target_sensor: sensor.house_temperature
    outdoor_sensor: sensor.climate_outdoor_temperature
    heater: input_number.boiler_output
    pwm: 0
    keep_alive:
      seconds: 60
    min_temp: 7
    max_temp: 25
    target_temp: 21
    away_temp: 14
    eco_temp: 10
    comfort_temp: 19
    home_temp: 21.5
    sleep_temp: 19
    activity_temp: 18
    sensor_stall: 00:30:00
    output_safety: 50.0
    debug: true

**Comment by andreid1303** [comment]
The logs:

`2024-12-04 20:02:33.032 INFO (MainThread) [custom_components.smart_thermostat.climate] climate.house_smart_thermostat: Change state of input_number.boiler_output to 100.0
2024-12-04 20:03:33.034 INFO (MainThread) [custom_components.smart_thermostat.climate] climate.house_smart_thermostat: Change state of input_number.boiler_output to 100.0
2024-12-04 20:04:16.543 INFO (MainThread) [custom_components.smart_thermostat.climate] climate.house_smart_thermostat: Obtained temperature 19.9 with set point 21.0. Activating SmartThermostat.
2024-12-04 20:04:16.543 INFO (MainThread) [custom_components.smart_thermostat.climate] climate.house_smart_thermostat: Change state of input_number.boiler_output to 46.4
2024-12-04 20:05:16.543 INFO (MainThread) [custom_components.smart_thermostat.climate] climate.house_smart_thermostat: Change state of input_number.boiler_output to 46.4
`
Is this by design?

**Comment by ScratMan** [comment]
Since 2024.6.0, the integral `pid_i` part can go negative down to external `-pid_e` to avoid overheating issues due to Ke gain. Hence the Ki and Ke gains might be readjusted.
Also, the integral part is cleared when set point is changed as it should converge to a new value.
This behaviour should help having faster reactivity on the heating by allowing higher Ki gains without overheating.

**Comment by andreid1303** [comment]
So on restart set point is updated from "unknown, unavailable " and integral is cleared, right?

**Comment by Chupaka** [comment]
> the integral part is cleared when set point is changed as it should converge to a new value

Well, if set point is changed, that should be covered by `pid_p`, and `pid_i` should continue from its current value. `pid_i` should characterize the system in a whole (like heat loss in case of a house), and not just the current state. Ideally, it should not change [significantly] if you update the set point...

**Comment by ScratMan** [comment]
The reset only occurs if external temperature is used, as the external part is taking the role of a kind of coarse integral, the standard integral is only there for fine adjustments.

@chmtc94 convinced me in his post on [another conversation].(https://github.com/ScratMan/HASmartThermostat/issues/150#issuecomment-1961535006)
That's what is applied now. I could confirm it works well on my four thermostats (driving electric on/off or gas boiler and water radiators with Netatmo valves), I just had to increase the Ke and Ki gains to compensate the pid_i being lower, and it increased integral reactivity.

**Comment by andreid1303** [comment]
Thank you. This have a sense. I will try to increase ke.
