### ISSUE TITLE
Precision not working 0.1 values

### ISSUE THREAD

**Issue by mupsje** [ScratMan/HASmartThermostat#27]
Precision not working.

```
precision (Optional): the displayed temperature precision (valid are 0.1, 0.5 and 1.0, default 0.1 for Celsius and 1.0 for Fahrenheit)
```

Not working at 0.1 values

**Comment by ScratMan** [comment]
Which temperature shows wrong precision ? Target temperature or current temperature ?

Please check with the two parameters below. The `precision` setting sets the accuracy of the current temperature display, rounding the temperature from the sensor. The `target_temp_step` setting selects the steps for the target temperature input (sliders or input boxes).

* **target_temp_step** (Optional): the adjustment step of target temperature (valid are 0.1, 0.5 and 1.0, default 0.5 for Celsius and 1.0 for Fahrenheit)
* **precision** (Optional): the displayed temperature precision (valid are 0.1, 0.5 and 1.0, default 0.1 for Celsius and 1.0 for Fahrenheit)
