### ISSUE TITLE
Reset integral if the set point changes?

### ISSUE THREAD

**Issue by maherran** [ScratMan/HASmartThermostat#276]
**Describe the bug**
When set point changes (see line 222 on file /pid_controller/\_init_.py), system is supposed to _Reset integral if set point has changed as system will need to converge to a new value_. But this only happens when having external temperature sensor:

_**if ext_temp is not None and** self._last_set_point != self._set_point:
            self._integral = 0_  

In my case, without external temperature sensor, this is not happening.

**To Reproduce**
1. Do not use external temperature sensor
2. Follow up sensor PID I
3. Change set point
4. See value on PID I sensor (not reseting)

**Expected behavior**
IMHO, if this way of working is supposed to be related to process, this should also happen even without having external temperature sensor.

**Screenshots**
Easy to test. No screenshot needed.

**Desktop (please complete the following information):**
 - OS: Home Assistant
 - Version 2024.12.5

**Comment by ScratMan** [comment]
That's normal behaviour. The automatic reset of integral is only supposed to occur when external temperature sensor is used (that means Ke != 0).
