### ISSUE TITLE
Integral part of the PID controller accumulates gain for error during the period the thermostat was in OFF state

### ISSUE THREAD

**Issue by jandado** [ScratMan/HASmartThermostat#38]
**Describe the bug**
I have three floor heating circuits regulated by the Smart Thermostat. I am forced to shut them down during peak hours. When the thermostat is turned back ON (usually after 1 hour) the temperature drop is accumulated into the integral part for the whole duration it was OFF. See attached recent chart of the pid_i attribute of one of the thermostats. The flat lines are during the OFF periods, the immediate jumps are right after it is turned back on. I have highlighted the parts I am referring to.

**To Reproduce**
1. turn thermostat OFF,
2. wait for the temperature to drop by one or a couple of degrees over a "significant" period (from the controller perspective, i.e. an hour),
3. turn back ON - the next pid_i update will jump by the overall accumulated error, including the off period.

**Expected behavior**
The integral part of the thermostat should not account for the time it has spent in the OFF state and keep the value unchanged until there is an update (temperature change / sampling period). It was obviously not missing the target temperature furing OFF period, because it could not act to achieve it.

**Screenshots*
![pid_i](https://user-images.githubusercontent.com/783185/144858530-123f1f0f-f3eb-4ff9-9184-a325f58e1c39.png)
*

**Comment by ScratMan** [comment]
Hi, it didn't integrate, the PID is not called nor refreshed while thermostat is off. But when you switch it back on, the last sample might be several hours or days old, so dt will become huge, and then the PID will multiply it by the new temperature error. I'll need to fix that.

**Comment by jandado** [comment]
> Hi, it didn't integrate, the PID is not called nor refreshed while thermostat is off. But when you switch it back on, the last sample might be several hours or days old, so dt will become huge, and then the PID will multiply it by the new temperature error. I'll need to fix that.

Hi @ScratMan  - yes, that is what I was trying to say :)
It causes wild over-shoots (even with no-overshoot autotuned parameters) and oscillations that take long time to settle.
Thank you!

**Comment by ScratMan** [comment]
Hello @jandado , please try this beta release https://github.com/ScratMan/HASmartThermostat/releases/tag/2021.12.2-beta1

**Comment by jandado** [comment]
I have just updated, @ScratMan - I will let you know how it goes.

**Comment by jandado** [comment]
Hello @ScratMan. It behaves much better now - see attached screenshot. There is one jump in the evening before the 2021.12.2-beta1, the black circle is cause by me calling smart_thermostat.clear_integral to have a fresh start. All the way on the right is todays behavior after one hour in off state. I made sure the temperature dropped by reasonably significant margin. The integral picks up where it should as it was turned back on.

Thank you!
![pid_i_2021 12 2-beta1](https://user-images.githubusercontent.com/783185/144985996-bda5165e-6853-4a59-bfdb-9855a0924c69.png)

**Comment by ScratMan** [comment]
Fix merged in [v2021.12.2](https://github.com/ScratMan/HASmartThermostat/releases/tag/2021.12.2)
