### ISSUE TITLE
Attributes are not updated after a calculation

### ISSUE THREAD

**Issue by bamnoru** [ScratMan/HASmartThermostat#39]
Hi,

**Describe the bug**
Attributes (control_output, pid_p, pid_i, pid_d) are not updated after a calculation.
Wait for a temperature update, attributes are updated.

**Expected behavior**
After each PID and output calculation, update attributes.

**Additional context**
Maybe, add at the end of "calc_output", line #804 :
await self.async_update_ha_state()

**Comment by ScratMan** [comment]
Should be fixed by [this commit](https://github.com/ScratMan/HASmartThermostat/commit/3ac4ed6defd5cdc20a86e21d345574f3ccd3e4b8)

**Comment by ScratMan** [comment]
Hello @bamnoru , please try this beta release : https://github.com/ScratMan/HASmartThermostat/releases/tag/2021.12.2-beta1

**Comment by bamnoru** [comment]
Hi @ScratMan ,
Thanks a lot.
Beta version installed.
Attributes are updated more frequently.
Need to wait, the major issue was when the control_output return to 0.

**Comment by bamnoru** [comment]
Hi,

Works fine, now, I can have some charts to analyse PID values and tune it.
