### ISSUE TITLE
Can I somehow get Control Output with both positive and negative values? 

### ISSUE THREAD

**Issue by MarkoPaasila** [ScratMan/HASmartThermostat#42]
**Is your feature request related to a problem? Please describe.**
I want to try using PID for controlling the target temperature of my heat pump. Currently it only gives either positive or negative output, and cuts out at zero.

**Describe the solution you'd like**
I would like to get a Control Output (using a template sensor), that works both ways.

**Describe alternatives you've considered**
I currently use a Python script with quasi-proportional control. I need it to warm up the surrounding air in excess, then switch to fan_only mode to spread it around the home. Otherwise it will just warm it's own surroundings to the target temperature, and everywhere else will be too cold. In the summer it's the opposite.

**Additional context**
I think PID is the right solution to my problem - and an elegant/cool one.

**Comment by ScratMan** [comment]
Why both positive and negative value ? a modulation can't be negative, it's either 0%, 100% or anything in-between. You can't have -20%.

**Comment by MarkoPaasila** [comment]
Positive for heating, negative for cooling. I didn't realize Control Output is modulation; I thought the P was for that purpose. Maybe I need to write a simple PID script that doesn't do on/off switching but outputs only target temperatures.

**Comment by ScratMan** [comment]
There is an AC mode already to cool down, but the thermostat can't do both at the same time, theoretically the AC is set to either heating or cooling modes.

Anyway, you may get the P, I and D components of the PID output in the thermostat's attributes using templates, and add them by yourself to get a negative value.

**Comment by MarkoPaasila** [comment]
Ok I'll do that. Thanks!
