### ISSUE TITLE
Strange behaviour after calling smart_thermostat: reload service

### ISSUE THREAD

**Issue by TTLucian** [ScratMan/HASmartThermostat#46]
**Describe the bug**
After calling smart_thermostat: reload service I get strange behaviour of the target temperature. It always reverts to the value before reload. Only a restart of the HA core resolves this problem.

**To Reproduce**
1. Call smart_thermostat: reload service
2. Change the target temperature
3. Wait a few seconds
4. The target temperature reverts by itself to the value set before the reload

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/1855276/145918446-5cc7ae78-4642-4c0c-af04-b7ac7dc8e013.jpg)

**Additional context**
I haven't found any other cause or corelation for this behaviour. I don't have any automations or scripts or schedules or other stuff that messes with the target temperature. I've looked everywhere. The generic_thermostat works fine. Everything is fine after a HA core restart but the issue comes right back after smart_thermostat: reload service.

**Comment by ScratMan** [comment]
Confirmed. Really strange, need to remove the reload service till the root cause is identified.
