### ISSUE TITLE
How to change presets?

### ISSUE THREAD

**Issue by widewing** [ScratMan/HASmartThermostat#5]
I installed and configured this component successfully, but what i can only do is set a target temperature, I see no where to change the defined presets.. I want to put it into sleep mode when I'm sleeping.

Also in the entity page, it suggests "This entity ('climate.smart_thermostat_living_room') does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail."

**Comment by ScratMan** [comment]
Hello, you need to change the configuration of the smart thermostat in the YAML file, to add the required preset temperatures.
You may use one or several of the parameters shown in the readme file :

* **away_temp** (Optional): Set the temperature used by the "Away" preset. If this is not specified, away_mode feature will not be available.
* **eco_temp** (Optional): Set the temperature used by the "Eco" preset. If this is not specified, eco feature will not be available.
* **boost_temp** (Optional): Set the temperature used by the "Boost" preset. If this is not specified, boost feature will not be available.
* **comfort_temp** (Optional): Set the temperature used by the "Comfort" preset. If this is not specified, comfort feature will not be available.
* **home_temp** (Optional): Set the temperature used by the "Home" preset. If this is not specified, home feature will not be available.
* **sleep_temp** (Optional): Set the temperature used by the "Sleep" preset. If this is not specified, sleep feature will not be available.
* **activity_temp** (Optional): Set the temperature used by the "Activity" preset. If this is not specified, activity feature will not be available.

Then the enable presets will be available in the thermostat entity panel as drop-down list as shown :
![Screenshot_2021-11-15-14-00-51-59_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/971926/141786455-1817b4b4-29a9-4a27-8582-66892e6d3880.jpg)

**Comment by widewing** [comment]
@ScratMan I set these items as in below configurations:
```
climate:
  - platform: smart_thermostat
    name: Smart Thermostat - Living Room
    heater: switch.living_room_heater
    target_sensor: sensor.ble_temperature_e72e0171f422
    min_temp: 7
    max_temp: 28
    ac_mode: False
    target_temp: 19
    keep_alive:
      seconds: 60
    away_temp: 0
    sleep_temp: 17
    home_temp: 19
    kp : 75
    ki : 0.001
    kd : 70000
    pwm : 00:15:00
 ```
However I see only Operation for heat or off:
![image](https://user-images.githubusercontent.com/4755389/141828458-8df17559-d5e4-4143-b675-213bba69949c.png)

**Comment by ScratMan** [comment]
What version are you using ? And did you restart HA after editing the YAML ?

**Comment by ScratMan** [comment]
I could reproduce the issue by setting away_temp to 0. The preset selector then disappears after restart.

**Comment by ScratMan** [comment]
Please update to release [v2021.11.7](https://github.com/ScratMan/HASmartThermostat/releases/tag/2021.11.7), it fixes this issue by allowing setting a preset temperature to 0.
