### ISSUE TITLE
[Feature request] Optional numerical output instead of ON/OFF

### ISSUE THREAD

**Issue by tobimai** [ScratMan/HASmartThermostat#6]
I have Radiator valves which can be controlled by a 0-100 percentage, so it would be nice if the Thermostat could also output these values, as I want to control the TRV with an external Sensor. 
 
So a numerical output, basically just the value which is then converted to PWM, would be very useful in my setup.

I don't know how difficult this is, or if you are interested in this feature but I just wanted to suggest it as the problem came up for me.

**Comment by ScratMan** [comment]
Hi, you may use a template to get the **control_output** attribute in HA
`{{ state_attr('climate.salle_de_bain', 'control_output') | float }}`
