### ISSUE TITLE
Preset values not updated

### ISSUE THREAD

**Issue by csmit86** [ScratMan/HASmartThermostat#62]
After changing the preset values in the configuration.yaml the thermostat still uses the previous values. 
I did restart HA. 

configuration.yaml

`climate:
  - platform: smart_thermostat
    name: Smart Thermostat
    unique_id: my_smart_thermostat
    heater: switch.verwarming
    target_sensor: sensor.thermometer
    outdoor_sensor: sensor.buienradar_temperature
    preset_sync_mode: sync
    target_temp_step: 0.1
    sampling_period: 900
    min_temp: 14
    max_temp: 21
    ac_mode: False
    keep_alive:
      seconds: 60
    comfort_temp: 20
    home_temp: 19
    eco_temp: 18
    away_temp: 14
    noiseband: 0.3
    kp : 100
    ki : 40
    kd : 60
`
<img width="421" alt="Screenshot 2022-01-01 at 12 05 24" src="https://user-images.githubusercontent.com/11189944/147849204-2a2eaad7-679d-4720-b127-310003cfa6b7.png">

**Comment by ScratMan** [comment]
This is expected behavior, once the presets are enabled by YAML, they are always restored from previous state after restart. The values should be changed by the `set_preset_temp` service only.

**Comment by csmit86** [comment]
Expected for you maybe. How should I have known?

**Comment by ScratMan** [comment]
You're right, I mentioned this in the description of the release when this feature was added, but I forgot to indicate it in the readme.
