### ISSUE TITLE
PWM calculation

### ISSUE THREAD

**Issue by AlexeiBaranov** [ScratMan/HASmartThermostat#63]
Wonderful job! 
I would like to give a little advice about autotune. My autotune calculated the coefficients well, but I did not know how to define appropriate PWM. However, that it is easy enough to define - just look at the autotune graph. if I understood correctly, then the average period of time during which the heater was active is the PWM (it was ~3h with my electric Kospel ECKO).  Is it worth mentioning in the documentation about the definition of PWM? I think it is possible to log it as one of autotune suggestions in the system log.

![image](https://user-images.githubusercontent.com/45144703/148772113-a767e262-21be-4481-8c0c-a384a63cb0fb.png)

**Comment by AlexeiBaranov** [comment]
Or am I wrong?

**Comment by ScratMan** [comment]
No, it seems the PWM period has no real link with the heating system. Except that it should be long enough to ensure that the high levels can generate enough power, but not too long or it would limit the accuracy of the modulation at lower levels. The 15 to 30 minutes range seems to be a good choice.

**Comment by LeoI5** [comment]
![image](https://github.com/ScratMan/HASmartThermostat/assets/77241781/5a1fc50e-2a1b-4bf8-85b3-3e9cc7837162)
I think PWM should be full period between two start heating
