### ISSUE TITLE
sleep_temp attribute change is ignored

### ISSUE THREAD

**Issue by basovink** [ScratMan/HASmartThermostat#73]
**Describe the bug**
sleep_temp: 12 is ignored and reset to sleep_temp: 15

**To Reproduce**
1. Define a smart_thermostat in .yaml with sleep_temp: 15
2. Restart Home Assistant
3. Edit the yaml to say sleep_temp: 12
4. Restart Home Assistant

**Expected behavior**
When selecting preset "sleep" from the dropdown in the frontend thermostat, I expect the temperature to be set to 12
When checking the state in developer tools, I expect the sleep_temp: attribute to be 12

**System:**
 - OS: HASSio on Raspberry 3B+
 - Browser: Firefox

**Additional context**
I also edited the attribute from the state editor. It gets reset to 15℃ always

**Comment by ScratMan** [comment]
Hello, the prese
