### ISSUE TITLE
Restart on specific preset

### ISSUE THREAD

**Issue by adi90x** [ScratMan/HASmartThermostat#78]
Hello,

First, thank for this very very nice job ! 
Just a quick question, Is there a way to make it start on a specific preset whenever it HA restart for example ?

Regards

**Comment by ScratMan** [comment]
Hi, you should use an automation triggered by HA startup, and using the service to set the desired preset. You could even select the preset based on time, date, or your location.

**Comment by T81** [comment]
You can use the `target_temp` parameter to preset the thermostat temperature after HA restarts
