### ISSUE TITLE
min_cycle_duration parameter possible?

### ISSUE THREAD

**Issue by nagyrobi** [ScratMan/HASmartThermostat#8]
Home Assistant's `generic_thermostat` integration has a great parameter named [min_cycle_duration](https://www.home-assistant.io/integrations/generic_thermostat/#min_cycle_duration) which is useful to prevent damage to the heating or cooling equipment due to too often switching it on and off.

I tried your component and this is how it behaves:
![kép](https://user-images.githubusercontent.com/1550668/141985601-914e15c2-bc76-457e-af4c-2b9773a1e468.png)

As you can see there are very short periods, of only a few seconds, for which the gas burner is turned off or on. This is problematic, because turning on the the gas burner is a process of at least 40-60 seconds (pump starts first for 20 seconds, pre-heats with small flame for another 20 seconds, and slowly increases flame to full afterwards). The PID algorithm makes too fast decisions, and turns on the gas for 30-40 seconds and it turns it off. Zero heat was sent to the house during during this. If this happens too fast the boiler will be damaged.

Normally one cycle of burning the gas for a central heating boiler should be at least 10 minutes, and after turning off another minimum 10 minutes should be waited before starting to burn again. This should be configurable with `min_cycle_duration` depending on the heating or cooling device type the user has.
Can you please add this kind of override to the component?

**Comment by ScratMan** [comment]
Hi, you're right, this is an important parameter. It has been removed from the base code a while ago.
I added it on a test version [v2021.11.8-beta1](https://github.com/ScratMan/HASmartThermostat/releases/tag/2021.11.8-beta1)
Could you please install and test this version and add this line to your smart_thermostat configuration and restart :
`min_cycle_duration: '00:10:00'`

By setting the log level in configuration.yaml like follows you should see some messages in log telling what the thermostat is trying to do (request to turn on/off the boiler) and what the heating control does (accepts on/off commands or reject if cycle is too short).

```
logger:
  default: info
  logs:
    custom_components.smart_thermostat: debug
```

Rgds

**Comment by nagyrobi** [comment]
Testing, thank you!

**Comment by ScratMan** [comment]
Please check the impact on the temperature regulation, it may have higher/longer overshoot.
Maybe it can be compensated by the PID gains.

**Comment by nagyrobi** [comment]
Looks good so far, I'll let it run for the night!

**Comment by ScratMan** [comment]
It may depend on the type of the heating system, radiators heating is fast and may overshoot a lot if the min cycle duration is longer than the computed PWM on time. Floor heating is much slower, so it should be almost seamless.

**Comment by nagyrobi** [comment]
I'll have to experiment, comparing with generic_thermostat which is a simple bang-bang controller.

**Comment by ScratMan** [comment]
I created a discussion with the beta version to discuss about that without overloading the issue.
https://github.com/ScratMan/HASmartThermostat/discussions/11

**Comment by nagyrobi** [comment]
I made this for scheduling: https://github.com/nagyrobi/home-assistant-configuration-examples/tree/main/heating looks like your component was the missing puzzle.

**Comment by nagyrobi** [comment]
I get this error in the log, since the update, but I have no clue where it comes from, because I have no `hc1.hatemp` in my system anywhere...

`2021-11-17 09:29:12 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'hatemp' when rendering '{{value_json.hc1.hatemp}}'`

**Comment by ScratMan** [comment]
[Official release done](https://github.com/ScratMan/HASmartThermostat/releases/tag/2021.11.8)

**Comment by nagyrobi** [comment]
Thank you.
