### ISSUE TITLE
Temperature history not updating properly

### ISSUE THREAD

**Issue by LeChuck2909** [ScratMan/HASmartThermostat#91]
**Describe the bug**
Since i updated HA to version 2022.9.7, the history view of the entity, where you can see the temperature history, and it fhe entity was heating, is not updating properly anymore, on some of my smart thermostats. The underlying temperature sensor is updating, though. Also when the entity "stuck" on a heating state, as in the screenshot below, it isnt actually heating, so i guess this just a dispaying isse.

**To Reproduce**
1. Update HA to version 2022.9.7

**Expected behavior**
Proper updating after the HA update

**Screenshots**
<img width="407" alt="image" src="https://user-images.githubusercontent.com/61522664/192697321-0750a451-49ba-4158-a588-6e48631bc7ff.png">

**Desktop (please complete the following information):**
 - OS: Home Assistant core  2022.9.7
 - Browser chrome
 - Version 105.0.5195.127

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LeChuck2909** [comment]
just found, that when i refresh my browser, with ctrl+shift+R, the graph is updating as well.

**Comment by teklabania** [comment]
I have exactly the same issue though it might be related to the frontend issue:
https://github.com/home-assistant/frontend/issues/13214

I need to restart HA app on my android device each time I want to see the proper graph.

Home Assistant 2022.9.7
Supervisor 2022.09.1
Frontend: 20220907.2

**Comment by karwosts** [comment]
I posted an explanation and user workaround for this in [13214](https://github.com/home-assistant/frontend/issues/13214#issuecomment-1349845701).

**Comment by ScratMan** [comment]
Can't reproduce issue. Might be related to HA version.

**Comment by mannebk79** [comment]
i have the same issue see #105, i close #105 as duplicate
