### ISSUE TITLE
Ability to reload entities by Developer Tools :: YAML configuration reloading

### ISSUE THREAD

**Issue by Masterz69** [ScratMan/HASmartThermostat#92]
Would be very nice to have ability to reload smart_thermostat entities by 'YAML configuration reloading', not by reloading HA Core.

Example of integration with such ability: dual_smart_thermostat.

**Comment by malinduta** [comment]
Yes, it would be nice.

**Comment by ScratMan** [comment]
I can't see in the code what enables the reloading of the dual_smart_thermostat integration

**Comment by ScratMan** [comment]
This has been fixed by commit d06f4ed887cd077fac9c8f195ec0a0d9bf0e3345
