### ISSUE TITLE
How to find the autotune_status attribute

### ISSUE THREAD

**Issue by dmshimself** [ScratMan/HASmartThermostat#93]
**Describe the bug**
The docs described started an autotune and looking at the autotune_status attribute to check the results.  I'm not able to find this attribute.  No devices appear to have been created and the single entities doesn't have any attributes I can see.  There are messages in the lo indicating the autotune is in progress.   Any thoughts on how to display this much appreciated.

**To Reproduce**
Create a smart thermostat as per the docs and give it a switch and sensor for temperate.
Add autotune: "brewing"	to the config
Restart HA and check the logs
Autotune indicates it has started.
Look for any entities with smart_therm integration and the single item created appears, but when displayed there are no attributes to view.
(No devices with the same integration are created)

**Expected behavior**
An attribute on the entity called autotune_status should be viewable

**Screenshots**
![Screenshot_2022-11-29_16-05-55](https://user-images.githubusercontent.com/6901481/204428879-347cdf5b-84c0-4d7c-8604-ef81b230f5f1.png)

**Desktop (please complete the following information):**
 - Home Assistant 2022.11.4
 - Browser is Chrome

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by ScratMan** [comment]
Please look in the "Development Tools" > "States" panel in Home Assistant. Search for your entity, the attributes should be displayed once the auto-tune initialization is finished (it takes a few temperature samples at startup to initialize the system).

**Comment by dmshimself** [comment]
Many thanks for that prompt advice and I can now see all the attributes just fine :-)
