### ISSUE TITLE
Multiple target temperature sensors support

### ISSUE THREAD

**Issue by mcarbonneaux** [ScratMan/HASmartThermostat#95]
There possibility to use multiple temperature sensor (like multiroom sensors with one gas heater)?

**Comment by mcarbonneaux** [comment]
i think that using min/max integration to group my captor can work with min value.

**Comment by ScratMan** [comment]
If you need multizone thermostat, you may have a look to [multizone-thermostat](https://github.com/vindaalex/multizone-thermostat)

**Comment by mcarbonneaux** [comment]
in fact i have thermostatic zigbee valve on each of my radiator with central gas heater.
i think pid is a good way to control the heater, but i have different temperature target (in fact each valve use pid to control the open of the valve) in different zone, and i'm searching a way to control heater to be open to reach the temperature of each valve and stop heating.
i've seen a method based on the the level of opening of the valve (my valve expose it) to switch off/on the heater.
